In [53]:
import pandas as pd
import numpy as np

In [49]:
covid_file = pd.read_excel("C:\\Users\\acerl\\OneDrive\\Documents\\WD_Data_all-COVID-19_Stellenbosch.xls")

In [50]:
covid_file

,hospital_number,Na,K,k,Clin,hco3std,ventilation,ventilation_mode,HbA1c,Albumin,...,hiv_new_diag,immunodeficiency,tb_1,copd,ckd,hospital_number.1,venti,ag_n,ag,153
0,121265060,131.0,5.6,4.60,96.0,27.5,High Flow,NaN,NaN,NaN,...,2.0,1.0,2.0,1.0,1.0,121265060,Non-invasive,7.5,13.1,NaN
1,38461596,128.0,3.1,3.00,98.0,29.4,Other,NaN,6.3,NaN,...,1.0,1.0,2.0,1.0,1.0,38461596,Non-invasive,0.6,3.7,NaN
2,87594446,128.0,3.9,3.20,97.0,29.1,High Flow,NaN,12.1,NaN,...,1.0,1.0,2.0,1.0,1.0,87594446,Non-invasive,1.9,5.8,NaN
3,42450692,135.0,3.9,3.30,114.0,19.1,Other,NaN,NaN,NaN,...,1.0,1.0,2.0,1.0,1.0,42450692,Non-invasive,1.9,5.8,NaN
4,24941833,134.0,4.7,4.10,103.0,28.1,Other,NaN,6.6,NaN,...,NaN,1.0,2.0,1.0,1.0,24941833,Non-invasive,2.9,7.6,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
485,89012926,133.0,5.2,5.20,94.0,NaN,Intubated,p-simv,NaN,NaN,...,NaN,1.0,2.0,1.0,2.0,89012926,Invasive,NaN,NaN,NaN
486,54123211,137.0,5.3,4.21,106.0,NaN,Other,NaN,NaN,NaN,...,NaN,1.0,2.0,1.0,1.0,54123211,Non-invasive,NaN,NaN,NaN
487,40583361,140.0,4.1,NaN,99.0,NaN,Intubated,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,40583361,Invasive,NaN,NaN,NaN
488,45449568,NaN,NaN,4.20,NaN,NaN,Intubated,p-simv,NaN,NaN,...,NaN,1.0,2.0,1.0,1.0,45449568,Invasive,NaN,NaN,NaN
489,22215800,136.0,5.6,4.70,NaN,23.9,Intubated,aprv,NaN,NaN,...,2.0,1.0,2.0,1.0,1.0,22215800,Invasive,NaN,NaN,NaN

In [51]:
covid_file.describe()

,hospital_number,Na,K,k,Clin,hco3std,HbA1c,Albumin,ALP,ALT,...,hiv_status_1,hiv_new_diag,immunodeficiency,tb_1,copd,ckd,hospital_number.1,ag_n,ag,153
count,4.900000e+02,482.000000,478.000000,471.000000,404.000000,417.000000,374.000000,97.000000,98.000000,458.000000,...,394.000000,65.000000,466.000000,466.000000,464.000000,465.00000,4.900000e+02,366.000000,366.000000,0.0
mean,8.681687e+07,137.201245,4.437448,3.824459,98.574257,26.064269,8.011765,30.556701,102.683673,64.310044,...,1.137056,1.092308,1.006438,1.991416,1.028017,1.04086,8.681687e+07,12.836885,17.239891,NaN
min,1.066405e+07,109.000000,2.800000,1.700000,76.000000,2.000000,4.700000,20.000000,37.000000,6.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,1.066405e+07,0.600000,3.700000,NaN
25%,4.826174e+07,134.000000,3.900000,3.400000,95.000000,24.100000,6.200000,26.000000,69.000000,21.000000,...,1.000000,1.000000,1.000000,2.000000,1.000000,1.00000,4.826174e+07,9.325000,13.700000,NaN
50%,7.473471e+07,137.000000,4.400000,3.800000,98.000000,26.700000,6.800000,31.000000,90.500000,32.500000,...,1.000000,1.000000,1.000000,2.000000,1.000000,1.00000,7.473471e+07,12.400000,16.849999,NaN
75%,1.249444e+08,140.000000,4.900000,4.200000,102.000000,28.800000,9.100000,34.000000,118.750000,50.750000,...,1.000000,1.000000,1.000000,2.000000,1.000000,1.00000,1.249444e+08,15.300000,19.600000,NaN
max,1.783412e+08,168.000000,8.300000,6.900000,134.000000,37.900000,21.600000,46.000000,313.000000,2948.000000,...,2.000000,2.000000,2.000000,2.000000,2.000000,2.00000,1.783412e+08,49.299999,54.000000,NaN
std,5.172874e+07,5.417205,0.730583,0.682898,6.313319,4.413974,2.646525,5.569577,48.464589,223.189609,...,0.344344,0.291712,0.080063,0.092349,0.165200,0.19818,5.172874e+07,5.449296,5.611997,NaN

In [52]:
covid_file.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 490 entries, 0 to 489
Columns: 154 entries, hospital_number to 153
dtypes: datetime64[ns](8), float64(112), int64(7), object(27)
memory usage: 589.7+ KB

In [57]:
columns_to_drop = ['discharge_2', 'icu_discharge_death']
covid_file.drop(columns=columns_to_drop, inplace=True)

KeyError: "['discharge_2', 'icu_discharge_death'] not found in axis"

In [58]:
label_encoder = LabelEncoder()
covid_file['discharge_death_encoded'] = label_encoder.fit_transform(covid_file['discharge_death'])
correlation_matrix = covid_file.corr()

# Extract correlations with 'discharge_death_encoded'
correlations_with_discharge_death = correlation_matrix['discharge_death_encoded'].sort_values(ascending=False)
print("Correlations with discharge_death_encoded:")
print(correlations_with_discharge_death)

ValueError: could not convert string to float: 'High Flow'

In [43]:
#Calculate the threshold for dropping columns
threshold = len(covid_file) / 2
threshold

245.0

In [44]:
# Check for missing values in each column
missing_values = covid_file.isnull().sum()
missing_values

hospital_number              0
Na                           8
K                           12
k                           19
Clin                        86
                          ...
venti                        0
ag_n                       124
ag                         124
153                        490
discharge_death_encoded      0
Length: 153, dtype: int64

In [45]:
# Open a file to write the missing values information
with open("missing_values.txt", "w") as f:
    for col in covid_file.columns:
        missing = covid_file[col].isnull().sum()
        if missing > 0:
            f.write(f"{col}: {missing}\n")

# Display the contents of the file
with open("missing_values.txt", "r") as f:
    print(f.read())

Na: 8
K: 12
k: 19
Clin: 86
hco3std: 73
ventilation_mode: 411
HbA1c: 116
Albumin: 393
ALP: 392
ALT: 32
AST: 257
Basophils: 12
Ca: 197
Creatinine: 8
DDimer: 26
Eosinophils: 416
Ferritin: 83
eGFR: 293
GGT: 412
Hb: 8
Hct: 84
INR: 77
Lymphocytes: 11
MCHC: 84
MCV: 8
Mg: 200
Monocytes: 11
MPV: 85
Platelets: 8
RCC: 84
Urea: 8
RCDW: 84
Ucreat: 432
TropT: 71
PTTRatio: 356
PCT: 34
WCC: 8
Tbili: 37
NTProBNP: 70
Neutrophils: 10
CRP: 16
Po: 243
Phos: 454
TP: 480
Cbili: 479
LDH: 455
CK: 489
Fe: 481
TRF: 480
Tsaturation: 481
UrineNa: 489
Upotassium: 489
Fibrinogen: 484
time: 29
fi02: 20
pf_ratio: 20
date_intub_1: 223
extubation_date_1: 462
date_1: 15
ph: 17
paco2: 17
pao2: 17
lactate: 25
so2c: 28
discharge_death: 2
date_tbh_disch_death_1: 2
length_of_stay_in_hospital: 2
dob: 7
age_at_admission_in_comple: 7
gender: 6
wave: 490
weights: 82
HIVstatus: 286
date: 21
antibiotics: 22
antifungals: 22
antivirals: 22
anticoagulants: 22
corticosteroids: 22
other_medications_select___1: 21
other_medications_select___2: 21
other_medications_select___3: 21
other_medications_select___4: 21
other_medications_select___5: 21
other_medications_select___6: 21
other_medications_select___7: 21
other_medications_select___8: 21
other_medications_select___9: 21
other_medications_select___10: 21
other_medications_select___11: 21
other_medications_select___12: 21
smoking_status: 217
alcohol: 284
symp_fever: 50
symp_cough: 51
symp_sore_throat: 51
symp_rhinorrhoea: 51
symp_myalgia: 51
symp_fatigue: 51
symp_headache: 51
symp_joint_pains: 51
symp_dyspnoea: 47
symp_nausea: 51
symp_vomiting: 51
symp_diarrhoea: 51
symp_severe_critical: 37
symp_oxyg_sat: 38
symp_pao2: 38
symp_bp_sys: 42
symp_bp_dias: 42
symp_temp: 32
symp_prot: 75
symp_haem: 73
acute_physiology_and_chron: 92
symp_pitt_bact: 93
sequential_organ_failure_a: 50
symp_acute_res: 48
septic_shock: 50
cardiogenic_shock: 49
dysrhythmias: 50
symp_glasgow: 35
symp_acute_kid: 43
hypertension: 24
asthma: 24
diab_mellitus: 23
diab_meli: 257
insulin_res: 26
isch_heart_dis: 24
hyperlipidaemia: 24
bmi: 31
ptld: 26
hiv_status_1: 96
hiv_new_diag: 425
immunodeficiency: 24
tb_1: 24
copd: 26
ckd: 25
ag_n: 124
ag: 124
153: 490

In [46]:
#Drop columns with more than 250 missing values
covid_file_cleaned = covid_file.dropna(axis=1, thresh=len(covid_file) - 250)

In [47]:
# Display the cleaned DataFrame
print("\nCleaned DataFrame (columns with more than 250 missing values dropped):")
print(covid_file_cleaned.head())

Cleaned DataFrame (columns with more than 250 missing values dropped):
   hospital_number     Na    K    k   Clin  hco3std ventilation  HbA1c    ALT  \
0        121265060  131.0  5.6  4.6   96.0     27.5   High Flow    NaN   52.0
1         38461596  128.0  3.1  3.0   98.0     29.4       Other    6.3   13.0
2         87594446  128.0  3.9  3.2   97.0     29.1   High Flow   12.1   42.0
3         42450692  135.0  3.9  3.3  114.0     19.1       Other    NaN  118.0
4         24941833  134.0  4.7  4.1  103.0     28.1       Other    6.6   36.0

   Basophils  ...  hiv_status_1  immunodeficiency  tb_1  copd  ckd  \
0       0.02  ...           2.0               1.0   2.0   1.0  1.0
1       0.04  ...           2.0               1.0   2.0   1.0  1.0
2       0.05  ...           2.0               1.0   2.0   1.0  1.0
3       0.08  ...           2.0               1.0   2.0   1.0  1.0
4       0.01  ...           1.0               1.0   2.0   1.0  1.0

   hospital_number.1         venti  ag_n    ag  discharge_death_encoded
0          121265060  Non-invasive   7.5  13.1                        0
1           38461596  Non-invasive   0.6   3.7                        0
2           87594446  Non-invasive   1.9   5.8                        0
3           42450692  Non-invasive   1.9   5.8                        1
4           24941833  Non-invasive   2.9   7.6                        0

[5 rows x 126 columns]

In [11]:
categorical_columns = covid_file.select_dtypes(include=['object', 'category']).columns
numeric_columns = covid_file.select_dtypes(include=['number']).columns

print(categorical_columns)
print(numeric_columns)

Index(['ventilation', 'ventilation_mode', 'time', 'icu_discharge_death',
       'discharge_death', 'discharge_2', 'gender', 'HIVstatus', 'date',
       'antibiotics', 'antifungals', 'antivirals', 'anticoagulants',
       'corticosteroids', 'other_medications_select___1',
       'other_medications_select___2', 'other_medications_select___3',
       'other_medications_select___4', 'other_medications_select___5',
       'other_medications_select___6', 'other_medications_select___7',
       'other_medications_select___8', 'other_medications_select___9',
       'other_medications_select___10', 'other_medications_select___11',
       'other_medications_select___12', 'venti'],
      dtype='object')
Index([  'hospital_number',                'Na',                 'K',
                       'k',              'Clin',           'hco3std',
                   'HbA1c',           'Albumin',               'ALP',
                     'ALT',
       ...
            'hiv_status_1',      'hiv_new_diag',  'immunodeficiency',
                    'tb_1',              'copd',               'ckd',
       'hospital_number.1',              'ag_n',                'ag',
                       153],
      dtype='object', length=119)

In [12]:
from numpy import datetime64, float64, int64
from sklearn.pipeline import Pipeline, make_pipeline
from sklearn.compose import ColumnTransformer, make_column_selector
from sklearn.impute import SimpleImputer

In [13]:
# Ensure column names are strings
covid_file.columns = covid_file.columns.astype(str)
# Define categorical pipeline
catPipe = Pipeline([
    ("impute", SimpleImputer(strategy="most_frequent")),
])
# Define quantitative pipeline
quantPipe = Pipeline([
    ("impute", SimpleImputer(strategy="median"))
])

# Combine pipelines in a ColumnTransformer
fullPipe = ColumnTransformer([
    ("quant", quantPipe, make_column_selector(dtype_include=[float64, int64])),
    ("cat", catPipe, make_column_selector(dtype_include=object))
])

# Fit and transform the data
piped = fullPipe.fit_transform(covid_file)

# Create a new DataFrame with transformed data
covid_file_transformed = pd.DataFrame(piped, columns=fullPipe.get_feature_names_out())

In [14]:
print(covid_file_transformed)

    quant__hospital_number quant__Na quant__K quant__k quant__Clin  \
0              121265060.0     131.0      5.6      4.6        96.0
1               38461596.0     128.0      3.1      3.0        98.0
2               87594446.0     128.0      3.9      3.2        97.0
3               42450692.0     135.0      3.9      3.3       114.0
4               24941833.0     134.0      4.7      4.1       103.0
..                     ...       ...      ...      ...         ...
485             89012926.0     133.0      5.2      5.2        94.0
486             54123211.0     137.0      5.3     4.21       106.0
487             40583361.0     140.0      4.1      3.8        99.0
488             45449568.0     137.0      4.4      4.2        98.0
489             22215800.0     136.0      5.6      4.7        98.0

    quant__hco3std quant__HbA1c quant__Albumin quant__ALP quant__ALT  ...  \
0             27.5          6.8           31.0       90.5       52.0  ...
1             29.4          6.3           31.0       90.5       13.0  ...
2             29.1         12.1           31.0       90.5       42.0  ...
3             19.1          6.8           31.0      148.0      118.0  ...
4             28.1          6.6           31.0       90.5       36.0  ...
..             ...          ...            ...        ...        ...  ...
485           26.7          6.8           31.0       90.5        7.0  ...
486           26.7          6.8           31.0       87.0       50.0  ...
487           26.7          6.8           31.0       90.5     2948.0  ...
488           26.7          6.8           31.0       90.5       32.5  ...
489           23.9          6.8           31.0       90.5       68.0  ...

    cat__other_medications_select___4 cat__other_medications_select___5  \
0                           Unchecked                         Unchecked
1                           Unchecked                         Unchecked
2                           Unchecked                         Unchecked
3                           Unchecked                         Unchecked
4                           Unchecked                         Unchecked
..                                ...                               ...
485                         Unchecked                         Unchecked
486                         Unchecked                         Unchecked
487                         Unchecked                         Unchecked
488                         Unchecked                         Unchecked
489                         Unchecked                         Unchecked

    cat__other_medications_select___6 cat__other_medications_select___7  \
0                             Checked                         Unchecked
1                             Checked                         Unchecked
2                           Unchecked                         Unchecked
3                           Unchecked                         Unchecked
4                             Checked                           Checked
..                                ...                               ...
485                         Unchecked                           Checked
486                         Unchecked                         Unchecked
487                         Unchecked                         Unchecked
488                         Unchecked                         Unchecked
489                         Unchecked                         Unchecked

    cat__other_medications_select___8 cat__other_medications_select___9  \
0                           Unchecked                         Unchecked
1                           Unchecked                         Unchecked
2                           Unchecked                         Unchecked
3                           Unchecked                         Unchecked
4                           Unchecked                         Unchecked
..                                ...                               ...
485                         Unchecked                         Unchecked
486                         Unchecked                         Unchecked
487                         Unchecked                         Unchecked
488                         Unchecked                         Unchecked
489                         Unchecked                         Unchecked

    cat__other_medications_select___10 cat__other_medications_select___11  \
0                            Unchecked                            Checked
1                            Unchecked                          Unchecked
2                            Unchecked                          Unchecked
3                            Unchecked                          Unchecked
4                            Unchecked                          Unchecked
..                                 ...                                ...
485                            Checked                          Unchecked
486                          Unchecked                          Unchecked
487                          Unchecked                          Unchecked
488                          Unchecked                          Unchecked
489                          Unchecked                          Unchecked

    cat__other_medications_select___12    cat__venti
0                            Unchecked  Non-invasive
1                              Checked  Non-invasive
2                            Unchecked  Non-invasive
3                              Checked  Non-invasive
4                            Unchecked  Non-invasive
..                                 ...           ...
485                          Unchecked      Invasive
486                          Unchecked  Non-invasive
487                            Checked      Invasive
488                          Unchecked      Invasive
489                          Unchecked      Invasive

[490 rows x 144 columns]

In [15]:
categorical_columns = covid_file.select_dtypes(include=['object']).columns
for col in categorical_columns:
    print(f"Categorical Column '{col}':")
    print(covid_file[col])
    print("\n")

Categorical Column 'ventilation':
0      High Flow
1          Other
2      High Flow
3          Other
4          Other
         ...
485    Intubated
486        Other
487    Intubated
488    Intubated
489    Intubated
Name: ventilation, Length: 490, dtype: object


Categorical Column 'ventilation_mode':
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
        ...
485    p-simv
486       NaN
487       NaN
488    p-simv
489      aprv
Name: ventilation_mode, Length: 490, dtype: object


Categorical Column 'time':
0      16:13
1      17:49
2      23:57
3      20:19
4      12:50
       ...
485    21:54
486    21:59
487      NaN
488    20:56
489    05:11
Name: time, Length: 490, dtype: object


Categorical Column 'icu_discharge_death':
0          Death
1          Death
2          Death
3      Discharge
4          Death
         ...
485        Death
486    Discharge
487        Death
488        Death
489        Death
Name: icu_discharge_death, Length: 490, dtype: object


Categorical Column 'discharge_death':
0          Death
1          Death
2          Death
3      Discharge
4          Death
         ...
485        Death
486    Discharge
487        Death
488        Death
489        Death
Name: discharge_death, Length: 490, dtype: object


Categorical Column 'discharge_2':
0        NaN
1        NaN
2        NaN
3      Other
4        NaN
       ...
485      NaN
486     Home
487      NaN
488      NaN
489      NaN
Name: discharge_2, Length: 490, dtype: object


Categorical Column 'gender':
0        Male
1      Female
2      Female
3      Female
4      Female
        ...
485    Female
486      Male
487    Female
488    Female
489    Female
Name: gender, Length: 490, dtype: object


Categorical Column 'HIVstatus':
0      positive
1           NaN
2           NaN
3           NaN
4      Negative
         ...
485         NaN
486         NaN
487         NaN
488         NaN
489         NaN
Name: HIVstatus, Length: 490, dtype: object


Categorical Column 'date':
0      2020-08-27 00:00:00
1      2020-07-08 00:00:00
2      2020-05-13 00:00:00
3      2020-07-17 00:00:00
4      2020-07-10 00:00:00
              ...
485    2020-10-14 00:00:00
486    1020-01-01 00:00:00
487                    NaN
488    2020-12-10 00:00:00
489    2020-11-04 00:00:00
Name: date, Length: 490, dtype: object


Categorical Column 'antibiotics':
0      Yes
1      Yes
2      Yes
3       No
4      Yes
      ...
485    Yes
486     No
487    NaN
488    Yes
489     No
Name: antibiotics, Length: 490, dtype: object


Categorical Column 'antifungals':
0       No
1       No
2       No
3       No
4       No
      ...
485     No
486     No
487    NaN
488     No
489     No
Name: antifungals, Length: 490, dtype: object


Categorical Column 'antivirals':
0       No
1      Yes
2       No
3      Yes
4      Yes
      ...
485     No
486     No
487    NaN
488     No
489     No
Name: antivirals, Length: 490, dtype: object


Categorical Column 'anticoagulants':
0      Yes
1      Yes
2      Yes
3      Yes
4      Yes
      ...
485    Yes
486     No
487    NaN
488    Yes
489    Yes
Name: anticoagulants, Length: 490, dtype: object


Categorical Column 'corticosteroids':
0      Yes
1      Yes
2      Yes
3      Yes
4      Yes
      ...
485    Yes
486     No
487    NaN
488     No
489    Yes
Name: corticosteroids, Length: 490, dtype: object


Categorical Column 'other_medications_select___1':
0      Unchecked
1        Checked
2        Checked
3      Unchecked
4        Checked
         ...
485    Unchecked
486    Unchecked
487          NaN
488    Unchecked
489    Unchecked
Name: other_medications_select___1, Length: 490, dtype: object


Categorical Column 'other_medications_select___2':
0        Checked
1        Checked
2        Checked
3        Checked
4        Checked
         ...
485      Checked
486    Unchecked
487          NaN
488    Unchecked
489      Checked
Name: other_medications_select___2, Length: 490, dtype: object


Categorical Column 'other_medications_select___3':
0      Unchecked
1      Unchecked
2      Unchecked
3      Unchecked
4      Unchecked
         ...
485    Unchecked
486    Unchecked
487          NaN
488    Unchecked
489    Unchecked
Name: other_medications_select___3, Length: 490, dtype: object


Categorical Column 'other_medications_select___4':
0      Unchecked
1      Unchecked
2      Unchecked
3      Unchecked
4      Unchecked
         ...
485    Unchecked
486    Unchecked
487          NaN
488    Unchecked
489    Unchecked
Name: other_medications_select___4, Length: 490, dtype: object


Categorical Column 'other_medications_select___5':
0      Unchecked
1      Unchecked
2      Unchecked
3      Unchecked
4      Unchecked
         ...
485    Unchecked
486    Unchecked
487          NaN
488    Unchecked
489    Unchecked
Name: other_medications_select___5, Length: 490, dtype: object


Categorical Column 'other_medications_select___6':
0        Checked
1        Checked
2      Unchecked
3      Unchecked
4        Checked
         ...
485    Unchecked
486    Unchecked
487          NaN
488    Unchecked
489    Unchecked
Name: other_medications_select___6, Length: 490, dtype: object


Categorical Column 'other_medications_select___7':
0      Unchecked
1      Unchecked
2      Unchecked
3      Unchecked
4        Checked
         ...
485      Checked
486    Unchecked
487          NaN
488    Unchecked
489    Unchecked
Name: other_medications_select___7, Length: 490, dtype: object


Categorical Column 'other_medications_select___8':
0      Unchecked
1      Unchecked
2      Unchecked
3      Unchecked
4      Unchecked
         ...
485    Unchecked
486    Unchecked
487          NaN
488    Unchecked
489    Unchecked
Name: other_medications_select___8, Length: 490, dtype: object


Categorical Column 'other_medications_select___9':
0      Unchecked
1      Unchecked
2      Unchecked
3      Unchecked
4      Unchecked
         ...
485    Unchecked
486    Unchecked
487          NaN
488    Unchecked
489    Unchecked
Name: other_medications_select___9, Length: 490, dtype: object


Categorical Column 'other_medications_select___10':
0      Unchecked
1      Unchecked
2      Unchecked
3      Unchecked
4      Unchecked
         ...
485      Checked
486    Unchecked
487          NaN
488    Unchecked
489    Unchecked
Name: other_medications_select___10, Length: 490, dtype: object


Categorical Column 'other_medications_select___11':
0        Checked
1      Unchecked
2      Unchecked
3      Unchecked
4      Unchecked
         ...
485    Unchecked
486    Unchecked
487          NaN
488    Unchecked
489    Unchecked
Name: other_medications_select___11, Length: 490, dtype: object


Categorical Column 'other_medications_select___12':
0      Unchecked
1        Checked
2      Unchecked
3        Checked
4      Unchecked
         ...
485    Unchecked
486    Unchecked
487          NaN
488    Unchecked
489    Unchecked
Name: other_medications_select___12, Length: 490, dtype: object


Categorical Column 'venti':
0      Non-invasive
1      Non-invasive
2      Non-invasive
3      Non-invasive
4      Non-invasive
           ...
485        Invasive
486    Non-invasive
487        Invasive
488        Invasive
489        Invasive
Name: venti, Length: 490, dtype: object

In [74]:
from sklearn.preprocessing import LabelEncoder

In [76]:
# Encoding categorical features
label_encoders = {}
for col in covid_file.select_dtypes(include=['object']).columns:
    le = LabelEncoder()
    covid_file[col] = le.fit_transform(covid_file[col])
    label_encoders[col] = le

In [77]:
features = covid_file.drop(columns=['icu_discharge_death']) 
target = covid_file['icu_discharge_death']

KeyError: "['icu_discharge_death'] not found in axis"

In [65]:
def chi_square_test(cat_feature):
    contingency_table = pd.crosstab(covid_file[cat_feature], covid_file['discharge_death'])
    chi2, p, dof, ex = chi2_contingency(contingency_table)
    return p

# List of categorical columns to test
categorical_cols = [col for col in covid_file.columns if col.startswith('cat__')]
chi_square_results = {col: chi_square_test(col) for col in categorical_cols}

print("Chi-square test results:")
for col, p_value in chi_square_results.items():
    print(f"{col}: p-value = {p_value}")

AttributeError: 'int' object has no attribute 'startswith'

In [69]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.metrics import accuracy_score

In [70]:
target = covid_file['target_column']
X_train, X_test, y_train, y_test = train_test_split(covid_file, target, test_size=0.2, random_state=42)

KeyError: 'target_column'

In [71]:
log_reg = LogisticRegression()
rand_forest = RandomForestClassifier()
grad_boost = GradientBoostingClassifier()

In [72]:
log_reg.fit(X_train, y_train)
rand_forest.fit(X_train, y_train)
grad_boost.fit(X_train, y_train)

NameError: name 'X_train' is not defined

In [73]:
y_pred_log_reg = log_reg.predict(X_test)
y_pred_rand_forest = rand_forest.predict(X_test)
y_pred_grad_boost = grad_boost.predict(X_test)

NameError: name 'X_test' is not defined

In [ ]:
print(f"Logistic Regression Accuracy: {accuracy_log_reg}")
print(f"Random Forest Accuracy: {accuracy_rand_forest}")
print(f"Gradient Boosting Accuracy: {accuracy_grad_boost}")